export enum ProjectWorkflowAction {
  SUBMIT = 'SUBMIT',
  START_REVIEW = 'START_REVIEW',
  REQUEST_CHANGES = 'REQUEST_CHANGES',
  RESUBMIT = 'RESUBMIT',
  APPROVE = 'APPROVE',
  ARCHIVE = 'ARCHIVE',
}

export enum SectionWorkflowAction {
  COMPLETE = 'COMPLETE',
  START_REVIEW = 'START_REVIEW',
  REQUEST_CHANGES = 'REQUEST_CHANGES',
  APPROVE = 'APPROVE',
}
